services: 
  laravel-app:
    build:
      context: ./workspace
      dockerfile: Dockerfile-${PHP_VERSION}
      args:
        APP_NAME: "laravel-app"
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - ${LARAVEL_APP_PATH}:/var/www/laravel-app
      - ./php/php.ini:/etc/php/${PHP_VERSION}/fpm/php.ini
    depends_on:
      - mysql
      - redis

  laravel-horizon:
    build:
      context: ./workspace
      dockerfile: Dockerfile-${PHP_VERSION}
      args:
        APP_NAME: "laravel-app"
    container_name: laravel-horizon
    restart: unless-stopped
    command: ["supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf" ]
    user: root
    volumes:
      - ${LARAVEL_APP_PATH}:/var/www/laravel-app
      - ./php/php.ini:/etc/php/${PHP_VERSION}/fpm/php.ini
      - ./supervisor:/etc/supervisor/conf.d
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:1.27.2
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ${LARAVEL_APP_PATH}/public:/var/www/laravel-app/public
      - ./nginx:/etc/nginx/templates
    environment:
      - NGINX_UPSTREAM_APP=laravel-app:9000
    depends_on:
      - laravel-app

  mysql:
    image: mysql:8.4.2
    platform: linux/amd64
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my-8.0.cnf:/etc/mysql/conf.d/my.cnf

  redis:
    image: redis:7.4
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - 'redis:/data'

volumes:
  mysql_data:
    driver: local
  redis:
    driver: local