FROM php:8.2-fpm

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C.UTF-8
ENV LC_CTYPE=C.UTF-8
ENV LANG=C.UTF-8
ENV LANGUAGE=C.UTF-8
ARG APP_NAME

# Install dependencies
RUN set -eux; \
    apt-get update; \
    apt-get install -qy apt-utils \
      curl \
      fonts-noto \
      fonts-noto-cjk \
      libzip-dev \
      supervisor \
      unzip \
      zip; \
    rm -rf /var/lib/apt/lists/*

# Install PHP Extensions
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions \
  @composer-2 \
  bcmath \
  exif \
  gd \
  grpc \
  imagick \
  mcrypt \
  pcntl \
  pdo_mysql \
  redis \
  xmlrpc \
  zip 

# Add user & group
RUN groupadd -g 1000 app && \
  useradd -u 1000 -g app -G www-data,root -s /bin/bash app

RUN mkdir -p /var/log/app && \
  chown -R www-data:www-data /var/log/app && \
  chmod g+w /var/log/app

USER app
WORKDIR /var/www/${APP_NAME}
